module.exports = new Map()
    .set(401, (d) => ({ errData: { path: d.path, code: d.status }, meta: { title: `401 - Unauthorized`, desc: `401 - Unauthorized`, url: `https://thefemdevs.com/errors/401` } }))
    .set(403, (d) => ({ errData: { path: d.path, code: 403, reason: 'You are banned from accessing this website.' }, meta: { title: `403 - Forbidden`, desc: `403 - Forbidden`, url: `https://thefemdevs.com/errors/403` } }))
    .set(404, (d) => ({ errData: { path: d.path }, meta: { title: '404 - Page Not Found', desc: '404 - Page Not Found', url: 'https://thefemdevs.com/errors/404' } }))
    .set(405, (d) => ({ errData: { path: d.path, allowedMethods: Object.keys(d.allowedMethods).map(m => m.toUpperCase()).join(', '), methodUsed: d.methodUsed }, meta: { title: '405 - Method Not Allowed', desc: '405 - Method Not Allowed', url: 'https://thefemdevs.com/errors/405' } }))
    .set(429, (_) => ({ meta: { title: '429 - Too Many Requests', desc: '429 - Too Many Requests', url: 'https://thefemdevs.com/errors/429' } }))
    .set(451, (d) => ({ errData: { path: d.path }, meta: { title: `451 - Forbidden for Legal Reasons`, desc: `Location Denied`, url: `https://thefemdevs.com/errors/location` } }))
    .set(501, (_) => ({ meta: { title: `501 - Internal Server Error`, desc: `501 - Internal Server Error`, url: `https://thefemdevs.com/errors/501` } }))