const
    assert = require('assert'),
    nodemailer = require('nodemailer'),
    router = require('express').Router(),
    htmlMinifier = require('html-minifier'),
    Auth = require('../../../functions/crypto'),
    htmlProcessor = require('node-html-parser');

class MailReqProcesser {
    static getAuth(ah) {
        return Object.fromEntries(Auth.decode(ah).split(':').slice(0, 2).map((x, i) => i == 0 ? ['user', `${x}@thefemdevs.com`] : ['pass', x]))
    }
    static from(header) {
        return Object.fromEntries(header.split(';').map(s => s.split(':')).map(([k, v]) => [k == 'a' ? 'address' : k == 'n' ? 'name' : k == 'r' ? 'replyTo' : null, v]).filter(([k, _]) => k !== null))
    }
    static async parseBody(body) {
        return body.text
            || await (async function () {
                if (!body.url && !body.html) return null;
                const url = new URL(body.url);
                const dom = htmlProcessor.parse(body.html || (await fetch(url).then(r => r.text())));
                dom.querySelectorAll(['link', 'form', 'meta', 'title', 'style', 'embed', 'input', 'script', 'iframe', 'object', 'button', 'noscript', ...(url.hostname == 'thefemdevs.com' ? ['body>hero', 'body>div'] : [])].join(',')).forEach(e => e.remove());
                if (url.hostname == 'thefemdevs.com') dom.querySelector('head').insertAdjacentHTML('beforeend', `<style>${(await fetch('https://cdn.thefemdevs.com/assets/css/d').then(r => r.text())).replace(HTMLSanatize, '')}</style>`)
                return htmlMinifier.minify(dom.toString(), {
                    collapseBooleanAttributes: true,
                    collapseInlineTagWhitespace: true,
                    collapseWhitespace: true,
                    includeAutoGeneratedTags: false,
                    minifyCSS: true,
                    minifyJS: true,
                    minifyURLs: true,
                    quoteCharacter: '"',
                    removeAttributeQuotes: true,
                    removeComments: true,
                    removeEmptyAttributes: true,
                    removeRedundantAttributes: true,
                    removeScriptTypeAttributes: true,
                    removeStyleLinkTypeAttributes: true,
                    removeTagWhitespace: true,
                    sortAttributes: true,
                    sortClassName: true,
                    useShortDoctype: true,
                })
            })()
    }
    static getTransporter(a) {
        return nodemailer.createTransport({
            auth: a,
            host: "smtp.forwardemail.net",
            port: 465,
            secure: true,
        })
    }
    static envlope(ts, f, t, s, b) {
        return Object.assign({}, {
            from: f,
            to: t,
            subject: s,
            encoding: 'utf-8',
            textEncoding: 'base64',
            envelope: { from: ts, to: t },
            sender: f,
            replyTo: { name: f.name, address: f.replyTo || f.address },
            [(b.startsWith('<')) ? 'html' : 'text']: b,
        })
    }
    static async Send(req, res) {
        const auth = this.getAuth(req.headers['x-user']);
        const from = this.from(req.headers['x-from']);
        const body = await this.parseBody(req.body);
        if (!auth || !from) return res.sendError(8);
        if (!body) return res.sendError(10);
        const { to, subject } = req.body;
        const type = auth.user.split('@')[0] == 'global'
        assert(auth.user == (type ? 'global@thefemdevs.com' : from.address))
        if (type) assert(Auth.completeHash(auth.pass) == 'B4GVZRTW86j4Ki_jeIe74Hyv7K8bKPV_lyTgHJmuVEoBwqtr3OhUTpa2MaRdU7qA9CwPc9UpoB3T_rfVhaGY9A')
        const trueFrom = { name: type ? 'Global Admin' : from.name, address: type ? '*@thefemdevs.com' : from.address }
        const transport = this.getTransporter(auth);
        transport.sendMail(this.envlope(trueFrom, from, to, subject, body));
        res.status(200).send("OK");
    }
}

router
    .post('/send', async (req, res) => {
        if (await req.checkPermissions(req, res, { multi: false, perm: 'Global::Role.Owner', allowMgr: true })) MailReqProcesser.Send(req, res);
    })

module.exports = router;